# Configuration for immich-rknn setup
name: immich-rknn
# Service definitions for the immich-rknn application
services:
  # Main Immich Server service configuration
  immich-server:
    container_name: immich-server # Name of the running container
    image: ghcr.io/immich-app/immich-server:v2.4.1 # Image to be used
    # rkmpp for accelerated transcoding
    security_opt: # enables full access to /sys and /proc, still far better than privileged: true
      - systempaths=unconfined
      - apparmor=unconfined
    group_add:
      - video
    devices:
      - /dev/rga:/dev/rga
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mpp_service:/dev/mpp_service
      #- /dev/mali0:/dev/mali0 # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
    ports: # Mapping ports from the host OS to the container
      - 2283:2283
    volumes: # Mounting directories for persistent data storage
      - /DATA/AppData/$AppID/upload:/usr/src/app/upload
      - /DATA/Gallery:/DATA/Gallery
      #- /etc/OpenCL:/etc/OpenCL:ro # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
      #- /usr/lib/aarch64-linux-gnu/libmali.so.1:/usr/lib/aarch64-linux-gnu/libmali.so.1:ro # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
    environment: # Setting environment variables
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
      DB_DATABASE_NAME: immich
      DB_PORT: "5432"
      REDIS_HOSTNAME: immich-redis
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
    depends_on: # Dependencies to ensure the order of service startup
      - redis
      - database
    restart: unless-stopped # Policy to restart unless stopped
    # Networks to be attached to the container
    networks:
      - immich_network
    x-casaos:
      envs:
        - container: DB_HOSTNAME
          description:
            en_us: 'Container Variable: DB_HOSTNAME'
        - container: DB_USERNAME
          description:
            en_us: 'Container Variable: DB_USERNAME'
        - container: DB_PASSWORD
          description:
            en_us: 'Container Variable: DB_PASSWORD'
        - container: DB_DATABASE_NAME
          description:
            en_us: 'Container Variable: DB_DATABASE_NAME'
        - container: DB_PORT
          description:
            en_us: 'Container Variable: DB_PORT'
        - container: REDIS_HOSTNAME
          description:
            en_us: 'Container Variable: REDIS_HOSTNAME'
        - container: IMMICH_MACHINE_LEARNING_URL
          description:
            en_us: 'Container Variable: IMMICH_MACHINE_LEARNING_URL'
      volumes:
        - container: /usr/src/app/upload
          description:
            en_us: 'Container Path: /usr/src/app/upload'
        - container: /DATA/Gallery
          description:
            en_us: 'Container Path: /DATA/Gallery'
      ports:
        - container: "2283"
          description:
            en_us: 'Container Port: 2283'
  # Configuration for Immich Machine Learning service
  immich-machine-learning:
    container_name: immich-machine-learning # Name of the running container
    image: ghcr.io/immich-app/immich-machine-learning:v2.4.1-rknn # Image to be used
    security_opt:
      - systempaths=unconfined
      - apparmor=unconfined
    devices:
      - /dev/dri:/dev/dri
    volumes: # Mounting directories for persistent data storage
      - /DATA/AppData/$AppID/model-cache:/cache
    environment: # Setting environment variables
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
      DB_DATABASE_NAME: casaos
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
      MACHINE_LEARNING_RKNN: True
      MACHINE_LEARNING_RKNN_THREADS: 1
    restart: unless-stopped # Policy to restart unless stopped
    # Networks to be attached to the container
    networks:
      - immich_network # Connects the container to a defined network
    x-casaos:
      envs:
        - container: DB_HOSTNAME
          description:
            en_us: 'Container Variable: DB_HOSTNAME'
        - container: DB_USERNAME
          description:
            en_us: 'Container Variable: DB_USERNAME'
        - container: DB_PASSWORD
          description:
            en_us: 'Container Variable: DB_PASSWORD'
        - container: DB_DATABASE_NAME
          description:
            en_us: 'Container Variable: DB_DATABASE_NAME'
        - container: DB_PORT
          description:
            en_us: 'Container Variable: DB_PORT'
        - container: REDIS_HOSTNAME
          description:
            en_us: 'Container Variable: REDIS_HOSTNAME'
        - container: MACHINE_LEARNING_RKNN
          description:
            en_us: 'Container Variable: MACHINE_LEARNING_RKNN'
        - container: MACHINE_LEARNING_RKNN_THREADS
          description:
            en_us: 'Container Variable: MACHINE_LEARNING_RKNN_THREADS'
      volumes:
        - container: /cache
          description:
            en_us: 'Container Path: /cache'
  # Configuration for Redis service
  redis:
    container_name: immich-redis # Name of the running container
    image: redis:6.2.20-alpine@sha256:2185e741f4c1e7b0ea9ca1e163a3767c4270a73086b6bbea2049a7203212fb7f # patched for CVE-2025-49844
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich_network # Connects the container to a defined network
  # Configuration for Database service
  database:
    container_name: immich-postgres # Name of the running container
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0 # Image to be used
    environment: # Setting environment variables
      POSTGRES_PASSWORD: casaos
      POSTGRES_USER: casaos
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes: # Mounting directories for persistent data storage
      - /DATA/AppData/$AppID/pgdata:/var/lib/postgresql/data
    restart: unless-stopped # Policy to always restart the container if it stops
    # CasaOS specific configuration for the database service
    networks:
      - immich_network # Connects the container to a defined network
    x-casaos:
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: 'Container Variable: POSTGRES_PASSWORD'
        - container: POSTGRES_USER
          description:
            en_us: 'Container Variable: POSTGRES_USER'
        - container: POSTGRES_DB
          description:
            en_us: 'Container Variable: POSTGRES_DB'
        - container: PG_DATA
          description:
            en_us: 'Container Variable: PG_DATA'
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: 'Container Path: /var/lib/postgresql/data'
networks: 
  # Defines network configurations for the services
  immich_network:
    driver: bridge # Uses bridge network driver
x-casaos:
  # Supported CPU architectures for this application
  architectures:
    - arm64
  # Main service for this application
  main: immich-server
  # Detailed description for the application
  description:
    en_us: Self-hosted photo and video storage.
  # Brief tagline for the application
  tagline:
    en_us: Immich using RKNN for machine learning
  # Developer's information
  developer: immich-app
  # Author of this particular configuration
  author: BigBearTechWorld & jsjllymxbl
  # Icon URL for the application
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/icon.png
  # Thumbnail image for the application (if any)
  thumbnail: ""
  # Tips for the application
  tips:
    before_install:
      en_us: |
        For Chinese users...

        可选: Immich 反向地理编码汉化

        1.在 https://github.com/ZingLix/immich-geodata-cn 根据使用说明下载 geodata.zip 和 i18n-iso-countries.zip

        2.解压并放入/DATA/AppData/$AppID

        3.在immich-server容器添加下列卷映射

          /DATA/AppData/$AppID/geodata:/build/geodata

          /DATA/AppData/$AppID/i18n-iso-countries/langs:/usr/src/app/server/node_modules/i18n-iso-countries/langs
  # Title for the application
  title:
    en_us: Immich
  # Category under which the application falls
  category: wxy-OEC
  # Default port mapping for the application
  port_map: "2283"
