name: jellyfin-rkmpp
services:
  jellyfin:
    devices:
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mpp_service:/dev/mpp_service
      - /dev/rga:/dev/rga
    image: nyanmisaka/jellyfin:latest-rockchip
    deploy:
      resources:
        reservations:
          memory: "256M"
    network_mode: bridge
    ports:
      - target: 8096
        published: "8097"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/cache
        target: /cache
      - type: bind
        source: /DATA/Media
        target: /media
    x-casaos:
      ports:
        - container: "8096"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP端口
      volumes:
        - container: /config
          description:
            en_us: Jellyfin config directory.
            zh_cn: Jellyfin配置目录
        - container: /cache
          description:
            en_us: Jellyfin cache directory.
            zh_cn: Jellyfin缓存目录
        - container: /media
          description:
            en_us: Jellyfin Media directory.
            zh_cn: Jellyfin媒体目录
    container_name: jellyfin
x-casaos:
  architectures:
    - arm64
  main: jellyfin
  author: jsjllymxbl
  category: wxy-OEC
  description:
    en_US: >
      Jellyfin stands out among media server applications for its fully
      open-source, free, and privacy-focused design. Unlike Emby and Plex,
      Jellyfin delivers robust media management, real-time transcoding, and
      granular multi-user permissions without subscription costs, operating
      independently of cloud services to ensure full user control over data. Its
      community-driven development and efficient resource usage enable smooth
      performance on low-end devices, making it the go-to choice for
      privacy-conscious and budget-savvy users.


      Picture your movies, TV shows, and music at your fingertips, accessible on any device. Jellyfin transforms your media collection into a personalized entertainment hub, surpassing traditional photo albums with a seamless browsing and playback experience.

      Jellyfin offers high-quality streaming, automatic metadata fetching, and personalized recommendations, all at no cost. It supports multiple users, each with their own media library, catering to the diverse needs of families or teams.

      Deploying Jellyfin on private cloud devices like Zima provides near-unlimited storage, smooth streaming, and secure multi-device access. For NAS enthusiasts or anyone looking to elevate their home media setup, Jellyfin is the perfect solution.
    zh_CN: >
      Jellyfin 在媒体服务器应用中脱颖而出，凭借其完全开源、免费和注重隐私的设计。与 Emby 和 Plex 不同，Jellyfin
      提供强大的媒体管理、实时转码和细粒度的多用户权限，无需订阅费用，且独立于云服务运行，确保用户对数据拥有完全控制权。其社区驱动的开发和高效的资源使用使其在低端设备上也能流畅运行，成为注重隐私和预算用户的首选。


      想象一下，您的电影、电视节目和音乐触手可及，可在任何设备上访问。Jellyfin 将您的媒体收藏转变为个性化的娱乐中心，超越传统相册，提供无缝的浏览和播放体验。

      Jellyfin 提供高质量的流媒体、自动元数据获取和个性化推荐，所有这些都是免费的。它支持多个用户，每个用户都有自己的媒体库，满足家庭或团队的多样化需求。

      在 Zima 等私有云设备上部署 Jellyfin 可提供近乎无限的存储、流畅的流媒体和安全的跨设备访问。对于 NAS 爱好者或任何希望提升家庭媒体设置的人来说，Jellyfin 是完美的解决方案。
  developer: Jellyfin
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/screenshot-3.png
  tagline:
    en_US: The personal Media System
    zh_CN: 个人媒体系统
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Jellyfin/thumbnail.png
  tips: {}
  title:
    en_us: Jellyfin
  index: /
  port_map: "8097"
